services:
  - type: web
    name: mmu-hostel-booking
    env: docker
    plan: free # or starter
    region: ohio # choose your preferred region
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: MMU_SMTP_HOST
        value: smtp.gmail.com
      - key: MMU_SMTP_PORT
        value: 587
      - key: MMU_SMTP_USER
        sync: false
      - key: MMU_SMTP_PASS
        sync: false
      - key: MMU_SMTP_ENCRYPTION
        value: tls
      - key: MMU_FROM_EMAIL
        value: no-reply@mmu.ac.ug
      - key: MMU_FROM_NAME
        value: MMU Hostel System
